### ISSUE TITLE
Todoリストエンティティ作成

### ISSUE THREAD

**Issue by t-morisawa** [t-morisawa/responder-todo#6]
# やること
 - Todoリストclassを作る
 - クラス設計は以下を参考にする

# クラス設計

## プロパティ
yaml
```
todolist:
 - checked: <bool>
   task: <string>
```

json
```
{"todolist": ["checked": <bool>, "task": <string>]}
```

## 例

```
todolist:
 - checked: True
   task: "買い物"
 - checked: False
   task: "洗濯"
```
